name: Generate docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false
