name: Generate docs

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Modify version
      run: ./gh-version.sh
    - id: Deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false
